@echo off
rem ============================================
rem PC auto-update release script (stage 260)
rem Builds NSIS Setup installer + latest.yml via electron-builder,
rem then upload the produced "im-client-setup-<version>.exe" in
rem admin web console -> "client update" page (platform PC),
press "enable" to publish; server regenerates latest.yml automatically.
rem NOTE: bump "version" in package.json before each release,
rem       and keep it in sync with the version_name typed in admin console.
rem Run AFTER build.bat has produced a working bin (same source tree).
rem ============================================
setlocal
cd /d "%~dp0"

set "ELECTRON_MIRROR=https://npmmirror.com/mirrors/electron/"
set "ELECTRON_BUILDER_BINARIES_MIRROR=https://npmmirror.com/mirrors/electron-builder-binaries/"
set "ELECTRON_BUILDER_CACHE=%~dp0builder-cache"

echo [1/3] obfuscate + encrypt main modules (node obfuscate.js) ...
node obfuscate.js
if errorlevel 1 (
    echo [ERROR] obfuscate failed, abort
    pause
    exit /b 1
)

echo [2/3] build NSIS installer (electron-builder --win --x64) ...
call npx electron-builder --win --x64
if errorlevel 1 (
    echo [ERROR] installer build failed
    pause
    exit /b 1
)

echo [3/3] done. artifacts in dist\ :
dir /b "%~dp0dist\im-client-setup-*.exe" 2>nul
dir /b "%~dp0dist\latest.yml" 2>nul
echo.
echo Upload the im-client-setup-*.exe in admin console (platform PC) and enable it.
echo (latest.yml is regenerated by the server on enable, no need to upload it.)
pause
